import { test, expect } from '@playwright/test';

test.describe('Records Management', () => {
  test.beforeEach(async ({ page }) => {
    // Login
    await page.goto('/login');
    await page.fill('input[placeholder="Email address"]', 'admin@spidersmart.com');
    await page.fill('input[placeholder="Password"]', 'admin123');
    await page.click('button:has-text("Sign In")');
    await expect(page).toHaveURL('/');
    
    // Navigate to Records page
    await page.click('a[href="/records"]');
    await expect(page.locator('h1')).toContainText('Records');
  });

  test('should create a new inventory record', async ({ page }) => {
    const boxBarcode = 'BOX' + Math.random().toString(36).substring(2, 9).toUpperCase();
    const fileBarcode = 'FILE' + Math.random().toString(36).substring(2, 10).toUpperCase();

    await page.click('button:has-text("Create Record")');

    // Fill the form
    // Since names are generated by react-hook-form register, 
    // we might need to use select based on labels if possible, 
    // or just use CSS selectors if names are stable.
    
    await page.selectOption('select[name="entity_type_id"]', { index: 1 });
    await page.selectOption('select[name="entity_id"]', { index: 1 });
    
    // Wait for departments to load after selecting entity
    await page.waitForTimeout(500); 
    await page.selectOption('select[name="department_id"]', { index: 1 });

    await page.fill('input[name="location"]', 'Test Rack 1');
    await page.fill('input[name="box_barcode"]', boxBarcode);
    await page.fill('input[name="file_barcode"]', fileBarcode);
    await page.fill('textarea[name="description"]', 'E2E Test Record Description');
    await page.fill('input[name="year"]', '2024');

    // Submit
    await page.click('button:has-text("Save Record")');

    // Verify success - check for toast or return to table
    // The table should eventually contain the new box barcode
    await expect(page.locator('table')).toContainText(boxBarcode);
  });

  test('should search and filter records', async ({ page }) => {
    // Assuming there is a search input
    const searchInput = page.locator('input[placeholder*="Search"]');
    if (await searchInput.isVisible()) {
      await searchInput.fill('spider');
      await page.keyboard.press('Enter');
      // Verify results
      await expect(page.locator('table')).toContainText(/spider/i);
    }
  });
});
