"""initial migration aligned with schema

Revision ID: 66dbd4566a9c
Revises: 
Create Date: 2026-04-26 20:48:56.386308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66dbd4566a9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'changes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'tamper_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('audit_logs_performed_by_fkey'), 'audit_logs', type_='foreignkey')
    op.alter_column('departments', 'entity_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('departments_entity_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.alter_column('entities', 'entity_code',
               existing_type=sa.SMALLINT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('inventory_records', sa.Column('legal_hold_by', sa.UUID(), nullable=True))
    op.add_column('inventory_records', sa.Column('legal_hold_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('inventory_records', 'entity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('inventory_records', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('inventory_records', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('inventory_records', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inventory_records', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('inventory_records', 'disposition_status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('inventory_records', 'custom_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_constraint(op.f('inventory_records_box_barcode_key'), 'inventory_records', type_='unique')
    op.drop_constraint(op.f('inventory_records_file_barcode_key'), 'inventory_records', type_='unique')
    op.create_index(op.f('ix_inventory_records_box_barcode'), 'inventory_records', ['box_barcode'], unique=True)
    op.create_index(op.f('ix_inventory_records_category_id'), 'inventory_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_file_barcode'), 'inventory_records', ['file_barcode'], unique=True)
    op.create_index(op.f('ix_inventory_records_record_type_id'), 'inventory_records', ['record_type_id'], unique=False)
    op.create_index(op.f('ix_inventory_records_retention_policy_id'), 'inventory_records', ['retention_policy_id'], unique=False)
    op.drop_constraint(op.f('inventory_records_created_by_fkey'), 'inventory_records', type_='foreignkey')
    op.drop_constraint(op.f('inventory_records_updated_by_fkey'), 'inventory_records', type_='foreignkey')
    op.drop_column('locations', 'description')
    op.add_column('record_type_fields', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('record_type_fields', sa.Column('label', sa.Text(), nullable=False))
    op.alter_column('record_type_fields', 'record_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('record_type_fields', 'created_at')
    op.drop_column('record_type_fields', 'field_name')
    op.create_unique_constraint(None, 'record_types', ['name'])
    op.drop_column('record_types', 'created_at')
    op.add_column('record_versions', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('record_versions', sa.Column('data_snapshot', sa.JSON(), nullable=False))
    op.add_column('record_versions', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('record_versions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('record_versions', 'record_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('record_versions_changed_by_fkey'), 'record_versions', type_='foreignkey')
    op.drop_column('record_versions', 'changed_at')
    op.drop_column('record_versions', 'changed_by')
    op.drop_column('record_versions', 'version_number')
    op.drop_column('record_versions', 'snapshot')
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('record_versions', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('record_versions', sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('record_versions', sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('record_versions', sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('record_versions_changed_by_fkey'), 'record_versions', 'users', ['changed_by'], ['id'])
    op.alter_column('record_versions', 'record_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('record_versions', 'created_at')
    op.drop_column('record_versions', 'created_by')
    op.drop_column('record_versions', 'data_snapshot')
    op.drop_column('record_versions', 'version')
    op.add_column('record_types', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record_types', type_='unique')
    op.add_column('record_type_fields', sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('record_type_fields', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('record_type_fields', 'record_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('record_type_fields', 'label')
    op.drop_column('record_type_fields', 'name')
    op.add_column('locations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('inventory_records_updated_by_fkey'), 'inventory_records', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(op.f('inventory_records_created_by_fkey'), 'inventory_records', 'users', ['created_by'], ['id'])
    op.drop_index(op.f('ix_inventory_records_retention_policy_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_record_type_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_file_barcode'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_category_id'), table_name='inventory_records')
    op.drop_index(op.f('ix_inventory_records_box_barcode'), table_name='inventory_records')
    op.create_unique_constraint(op.f('inventory_records_file_barcode_key'), 'inventory_records', ['file_barcode'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('inventory_records_box_barcode_key'), 'inventory_records', ['box_barcode'], postgresql_nulls_not_distinct=False)
    op.alter_column('inventory_records', 'custom_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('inventory_records', 'disposition_status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'ACTIVE'::text"))
    op.alter_column('inventory_records', 'tags',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
    op.alter_column('inventory_records', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory_records', 'location',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory_records', 'department',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inventory_records', 'entity',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('inventory_records', 'legal_hold_at')
    op.drop_column('inventory_records', 'legal_hold_by')
    op.alter_column('entities', 'entity_code',
               existing_type=sa.String(),
               type_=sa.SMALLINT(),
               existing_nullable=False)
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_entity_id_fkey'), 'departments', 'entities', ['entity_id'], ['id'])
    op.alter_column('departments', 'entity_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(op.f('audit_logs_performed_by_fkey'), 'audit_logs', 'users', ['performed_by'], ['id'])
    op.alter_column('audit_logs', 'tamper_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'changes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'performed_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
