"""add search vector and saved searches

Revision ID: f2f70f4229bc
Revises: 66dbd4566a9c
Create Date: 2026-04-26 21:24:31.126985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2f70f4229bc'
down_revision: Union[str, Sequence[str], None] = '66dbd4566a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_searches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('inventory_records', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(description, '') || ' ' || coalesce(entity, '') || ' ' || coalesce(department, '') || ' ' || coalesce(location, '') || ' ' || coalesce(box_barcode, '') || ' ' || coalesce(file_barcode, ''))", persisted=True), nullable=True))
    op.create_index('ix_inventory_records_search_vector', 'inventory_records', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_records_search_vector', table_name='inventory_records', postgresql_using='gin')
    op.drop_column('inventory_records', 'search_vector')
    op.drop_table('saved_searches')
    # ### end Alembic commands ###
